package com.wdb007.baseservice.model;

import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonProperty;

public class BookInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book_info.isbn_no
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	@JsonProperty("isbn_no")
	private String isbnNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book_info.book_name
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	@JsonProperty("book_name")
	private String bookName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book_info.author
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	@JsonProperty("author")
	private String author;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book_info.press
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	private String press;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book_info.publication_date
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	@JsonProperty("publication_date")
	private Date publicationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book_info.category
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	@JsonProperty("category")
	private String category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book_info.price
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book_info.readable
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	private String readable;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book_info.imgurl
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	private String imgurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book_info.create_time
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	@JsonProperty("create_time")
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book_info.modify_time
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	@JsonProperty("modify_time")
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column book_info.describe
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	private String describe;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book_info.isbn_no
	 * @return  the value of book_info.isbn_no
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public String getIsbnNo() {
		return isbnNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book_info.isbn_no
	 * @param isbnNo  the value for book_info.isbn_no
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public void setIsbnNo(String isbnNo) {
		this.isbnNo = isbnNo == null ? null : isbnNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book_info.book_name
	 * @return  the value of book_info.book_name
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public String getBookName() {
		return bookName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book_info.book_name
	 * @param bookName  the value for book_info.book_name
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public void setBookName(String bookName) {
		this.bookName = bookName == null ? null : bookName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book_info.author
	 * @return  the value of book_info.author
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public String getAuthor() {
		return author;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book_info.author
	 * @param author  the value for book_info.author
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public void setAuthor(String author) {
		this.author = author == null ? null : author.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book_info.press
	 * @return  the value of book_info.press
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public String getPress() {
		return press;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book_info.press
	 * @param press  the value for book_info.press
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public void setPress(String press) {
		this.press = press == null ? null : press.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book_info.publication_date
	 * @return  the value of book_info.publication_date
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public Date getPublicationDate() {
		return publicationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book_info.publication_date
	 * @param publicationDate  the value for book_info.publication_date
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public void setPublicationDate(Date publicationDate) {
		this.publicationDate = publicationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book_info.category
	 * @return  the value of book_info.category
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book_info.category
	 * @param category  the value for book_info.category
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public void setCategory(String category) {
		this.category = category == null ? null : category.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book_info.price
	 * @return  the value of book_info.price
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book_info.price
	 * @param price  the value for book_info.price
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book_info.readable
	 * @return  the value of book_info.readable
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public String getReadable() {
		return readable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book_info.readable
	 * @param readable  the value for book_info.readable
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public void setReadable(String readable) {
		this.readable = readable == null ? null : readable.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book_info.imgurl
	 * @return  the value of book_info.imgurl
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public String getImgurl() {
		return imgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book_info.imgurl
	 * @param imgurl  the value for book_info.imgurl
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public void setImgurl(String imgurl) {
		this.imgurl = imgurl == null ? null : imgurl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book_info.create_time
	 * @return  the value of book_info.create_time
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book_info.create_time
	 * @param createTime  the value for book_info.create_time
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book_info.modify_time
	 * @return  the value of book_info.modify_time
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book_info.modify_time
	 * @param modifyTime  the value for book_info.modify_time
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column book_info.describe
	 * @return  the value of book_info.describe
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public String getDescribe() {
		return describe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column book_info.describe
	 * @param describe  the value for book_info.describe
	 * @mbg.generated  Fri Sep 22 13:41:18 CST 2017
	 */
	public void setDescribe(String describe) {
		this.describe = describe == null ? null : describe.trim();
	}
}